# <span style="color:red"> DATASCI 151 - Practice Quiz #5 </span>

<font size = "4" >
This quiz is open book 

<br>

- You <span style="color:red"> CAN </span> use all material from the course repo

- You should <span style="color:red"> NOT </span> use other resources outside the course repo.

- You should <span style="color:red"> NOT </span> collaborate with other students

- Use of LLMs or any AI tools is <span style="color:red"> NOT ALLOWED </span>

- To get full credit, the code should work as intended. But try to attempt every problem - you can still receive partial credit.

<br>

Print the following string:

"I will abide by Emory's code of conduct"

In [2]:
print("I will abide by Emory's code of conduct")

I will abide by Emory's code of conduct

In [3]:
# import necessary libraries here
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt

# for problem (a)
import statsmodels.formula.api as smf

<font size = "4">

**Q1** Recode a numeric column

<font size = "3">

- Read in the file "movies.csv" from the `quiz_data` folder, saving it as a DataFrame.

- Recode the "year" variable to create a new variable called "time_period" with the following categories.

$\qquad$ ``` ["1941-1967","1968-2003","2004-onwards"] ```

- You must use the `pd.cut` function to recode this variable.

- Print the DataFrame to the screen to check your answers

In [19]:
# your code here
# when doing right = True (you are saying you are including the right interval)
# when right is false, it means the interval is inclusive on the left 
df_movies = pd.read_csv("quiz_data/movies.csv")
#need 4 bins

lat_bins = [1940, 1968, 2004, np.inf]
lat_labels = ["1941-1967", "1968-2003", "2004-onwards"]

df_movies["time_period"] = pd.cut(df_movies["year"], 
                                bins = lat_bins,
                                right = False,
                                labels = lat_labels)
df_movies[["time_period","year"]]

     time_period  year
0   2004-onwards  2023
1      1941-1967  1941
2   2004-onwards  2017
3   2004-onwards  2017
4   2004-onwards  2004
5      1968-2003  2003
6      1941-1967  1967
7      1941-1967  1964
8      1968-2003  1977
9      1968-2003  1977
10     1968-2003  1986

<font size = "4">

**Q2** Aggregate and Sort

<font size = "3">

- Continue to use the DataFrame from the previous question.

- Do the following in a **single line of code** using chaining:

    - Group the data by "country"
    
    - Aggregate the following statistics: average runtime, maximum runtime, average IMDB score, minimum IMDB score

    - Sort by average IMDB score in **descending order**

- Print the resulting DataFrame to the screen

**Note:** A "single line of code" can continue on to the next line if you use a backslash or wrap the line within a pair of parentheses.

In [5]:
# your code here
df_movies.groupby(by = "country").agg(
    runtime_mean = ('runtime(minutes)', 'mean'),
    runtime_max = ('runtime(minutes)','max'),
    imdb_mean = ('imdb_score', 'mean'),
    imdb_min = ('imdb_score', 'min'),
).sort_values(by = 'imdb_mean', ascending = False)

          runtime_mean  runtime_max  imdb_mean  imdb_min
country
American    115.000000          120   7.900000       7.7
Italy        98.000000           98   7.300000       7.3
Japan        88.000000           88   7.200000       7.2
Korean      117.500000          120   7.200000       7.1
France       98.333333          108   7.033333       6.4
Thailand     97.000000           97   7.000000       7.0

<font size = "4">

**Q3** Subsetting data

<font size = "3">

- Continue to use the DataFrame from the previous question.

- Do the following in a **single line of code** using chaining:

    - Subset the observations for 'country == "France" using ```.query()```

    - Sort the values by year (oldest first)

    - Extract the two oldest movies

In [6]:
# your code here
# lecture_17 (iloc)
df_movies.query('country == "France"').sort_values(by = "year", ascending = True).iloc[[0,1],:]

,title,country,runtime(minutes),year,imdb_score,time_period
7,The Umbrellas of Cherbourg,France,91,1964,7.8,1941-1967
6,La Chinoise,France,96,1967,6.9,1941-1967

<font size = "4">

**Q4** Aggregate and query

<font size = "3">

- Read in the file "sprint_results.csv" from the `quiz_data` folder, saving it as a DataFrame.

- Do the following in a single line using chaining:

    - Extract the subset with constructorId equal to 51.

    - Aggregate the maximum number of laps and average number of laps for each driver in the subset.

    - Extract the subset of these drivers with maximum # of laps $\geq 20$.

In [7]:
# your code here
df_sprint = pd.read_csv("quiz_data/sprint_results.csv")
df_sprint.query('constructorId == 51').groupby(by = "driverId").agg(
    laps_max = ('laps', 'max'),
    laps_mean = ('laps', 'mean'),
).query('laps_max >= 20 ')

          laps_max  laps_mean
driverId
8               24  20.500000
822             23  22.000000
841             24  19.666667
855             23  11.500000

<font size = "4">

**Q5** Calculate race duration

<font size = "3">

- Read in the file "results_cleaned.csv" from the `quiz_data` folder, saving it as a DataFrame.

- The "milliseconds" column shows the race duration for each result measured in milliseconds. Create a new column called "race_duration_minutes" where we convert the race duration to minutes by dividing each millisecond value by 60,000 (which equals $6 \times 10^4$). Equivalently, you can multiply each millisecond value by $6 \times 10^{-4}$

- Group the data by **both** "raceId" and "constructorId" and calculate the average race duration in minutes for each group.

- Sort the data in descending order and then extract the raceId/constructorId pairs with the 5 slowest average times.

In [8]:
# your code here
df_results = pd.read_csv("quiz_data/results_cleaned.csv")
df_results["race_duration_minutes"] = df_results["milliseconds"]/60000
df_results.groupby(["raceId","constructorId"]).agg(
    race_duration_minutes_mean = ('race_duration_minutes', 'mean')
).sort_values(by = 'race_duration_minutes_mean', ascending = False).iloc[[0,1,2,3,4],:]

                      race_duration_minutes_mean
raceId constructorId
818    129                            251.509000
       107                            248.783000
847    15                             245.466258
       3                              245.410900
       5                              245.350783

<font size = "4">

**Q6** Aggregate custom statistic

<font size = "3">

- Continue to use the DataFrame corresponding to the data in "results_cleaned.csv".

- When a driver finishes 1st, 2nd, or 3rd it is known as a "podium finish". Write a function that takes in a Pandas Series and returns the number of entries $\leq 3$.

- Group by "driverId" and then aggregate the following statistics: the average of the "points" column, and the number of podium finishes in the "positionOrder" column - use your custom function for this second statistic.

- Merge the aggregated data back into the original DataFrame.

In [9]:
# your code here
df_results = pd.read_csv("quiz_data/results_cleaned.csv")
def podium_finish(val):
    for k in val:
        finishes = 0 
        if k <= 3:
            finishes += 1
        return finishes

group_agg = df_results.groupby(by = "driverId").agg(
    points_mean = ('points', 'mean'),
    podium_finish = ( 'positionOrder', podium_finish)
)

In [10]:
group_agg = df_results.groupby(by = "driverId").agg(
    points_mean = ('points', 'mean'),
    podium_finish = ( 'positionOrder', podium_finish))

df_results = pd.merge(left = group_agg, right = df_results, how = "left", on = "driverId")
df_results

,driverId,points_mean,podium_finish,resultId,raceId,constructorId,number,grid,position,positionText,positionOrder,points,laps,time,milliseconds,fastestLap,rank,fastestLapTime,fastestLapSpeed,statusId
0,1,14.313953,1,1,18,1,22,1,1,1,1,10.0,58,1:34:50.616,5690616.0,39,2,1:27.452,218.300,1
1,1,14.313953,1,27,19,1,22,9,5,5,5,4.0,56,+46.548,5525103.0,53,3,1:35.462,209.033,1
2,1,14.313953,1,57,20,1,22,3,13,13,13,0.0,56,\N,NaN,25,19,1:35.520,203.969,11
3,1,14.313953,1,69,21,1,22,5,3,3,3,6.0,66,+4.187,5903238.0,20,3,1:22.017,204.323,1
4,1,14.313953,1,90,22,1,22,3,2,2,2,8.0,58,+3.779,5213230.0,31,2,1:26.529,222.085,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25655,855,0.384615,0,25573,1082,51,24,10,8,8,8,4.0,70,+26.952,5808709.0,60,7,1:16.927,204.084,1
25656,855,0.384615,0,25604,1083,51,24,9,\N,R,19,0.0,0,\N,NaN,\N,0,\N,\N,4
25657,855,0.384615,0,25619,1084,51,24,13,14,14,14,0.0,70,\N,NaN,50,9,1:09.380,224.053,11
25658,855,0.384615,0,25641,1085,51,24,16,16,16,16,0.0,47,\N,NaN,25,18,1:39.368,211.649,16
25659,855,0.384615,0,25658,1086,51,24,12,13,13,13,0.0,69,\N,NaN,58,5,1:22.029,192.268,11