# <span style="color:red"> DATASCI 151 - Practice Quiz #5 </span>

<font size = "4" >
This quiz is open book 

<br>

- You <span style="color:red"> CAN </span> use all material from the course repo

- You should <span style="color:red"> NOT </span> use other resources outside the course repo.

- You should <span style="color:red"> NOT </span> collaborate with other students

- Use of LLMs or any AI tools is <span style="color:red"> NOT ALLOWED </span>

- To get full credit, the code should work as intended. But try to attempt every problem - you can still receive partial credit.

<br>

Print the following string:

"I will abide by Emory's code of conduct"

In [319]:
print("I will abide by Emory's code of conduct")

I will abide by Emory's code of conduct

In [320]:
# import necessary libraries here
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt

# for problem (a)
import statsmodels.formula.api as smf

<font size = "4">

**Q1** Recode a numeric column

<font size = "3">

- Read in the file "movies.csv" from the `quiz_data` folder, saving it as a DataFrame.

- Recode the "year" variable to create a new variable called "time_period" with the following categories.

$\qquad$ ``` ["1941-1967","1968-2003","2004-onwards"] ```

- You must use the `pd.cut` function to recode this variable.

- Print the DataFrame to the screen to check your answers

In [321]:
# your code here
df_movies = pd.read_csv("quiz_data/movies.csv")
print(df_movies)

# lat labels must be one fewer than lat bins
years = [1941, 1967,2004, 2017,1964, 1977, 1986, 2003]

lat_bins1 = [1940, 1967,2003, np.inf]
lat_labels1 = ["1941-1967", "1968-2003", "2004-onwards"]


df_movies["time_period"] = pd.cut(df_movies["year"],
                                  bins = lat_bins1,
                                  right = True,
                                  labels = lat_labels1)


df_movies["time_period"]

                         title   country  runtime(minutes)  year  imdb_score
0                   Past Lives  American               106  2023         7.8
1                 Citizen Kane  American               119  1941         8.2
2                      Revenge    France               108  2017         6.4
3                         Okja    Korean               120  2017         7.3
4                      Shutter  Thailand                97  2004         7.0
5        A Tale of Two Sisters    Korean               115  2003         7.1
6                  La Chinoise    France                96  1967         6.9
7   The Umbrellas of Cherbourg    France                91  1964         7.8
8                        House     Japan                88  1977         7.2
9                     Suspiria     Italy                98  1977         7.3
10                 Blue Velvet  American               120  1986         7.7

0     2004-onwards
1        1941-1967
2     2004-onwards
3     2004-onwards
4     2004-onwards
5        1968-2003
6        1941-1967
7        1941-1967
8        1968-2003
9        1968-2003
10       1968-2003
Name: time_period, dtype: category
Categories (3, object): ['1941-1967' < '1968-2003' < '2004-onwards']

<font size = "4">

**Q2** Aggregate and Sort

<font size = "3">

- Continue to use the DataFrame from the previous question.

- Do the following in a **single line of code** using chaining:

    - Group the data by "country"
    
    - Aggregate the following statistics: average runtime, maximum runtime, average IMDB score, minimum IMDB score

    - Sort by average IMDB score in **descending order**

- Print the resulting DataFrame to the screen

**Note:** A "single line of code" can continue on to the next line if you use a backslash or wrap the line within a pair of parentheses.

In [332]:
# your code here
df_movies.groupby(by = "country")

result = df_movies.groupby(by = "country").agg(
        average_runtime = ('runtime(minutes)', 'mean'),
        maximum_runtime = ('runtime(minutes)', 'max'),
        average_imdb = ('imdb_score', 'mean'),
        minimum_imdb = ('imdb_score', 'min')).round(2)        

print(result)

          average_runtime  maximum_runtime  average_imdb  minimum_imdb
country
American           115.00              120          7.90           7.7
France              98.33              108          7.03           6.4
Italy               98.00               98          7.30           7.3
Japan               88.00               88          7.20           7.2
Korean             117.50              120          7.20           7.1
Thailand            97.00               97          7.00           7.0

<font size = "4">

**Q3** Subsetting data

<font size = "3">

- Continue to use the DataFrame from the previous question.

- Do the following in a **single line of code** using chaining:

    - Subset the observations for 'country == "France" using ```.query()```

    - Sort the values by year (oldest first)

    - Extract the two oldest movies

In [323]:
# your code here
# 죽어도 까먹지 말기: when extracting rows from a table --> iloc 
df_movies.query("country == 'France'").sort_values(by = "year", ascending = True).iloc[0:2]

,title,country,runtime(minutes),year,imdb_score,time_period
7,The Umbrellas of Cherbourg,France,91,1964,7.8,1941-1967
6,La Chinoise,France,96,1967,6.9,1941-1967

<font size = "4">

**Q4** Aggregate and query

<font size = "3">

- Read in the file "sprint_results.csv" from the `quiz_data` folder, saving it as a DataFrame.

- Do the following in a single line using chaining:

    - Extract the subset with constructorId equal to 51.

    - Aggregate the maximum number of laps and average number of laps for each driver in the subset.

    - Extract the subset of these drivers with maximum # of laps $\geq 20$.

In [324]:
# your code here
df_sprints = pd.read_csv("quiz_data/sprint_results.csv")
result = df_sprints.query("constructorId == 51").agg(
    laps_max = ('laps', 'max'),
    laps_average = ('laps', 'mean')
).iloc[:1]


result

          laps
laps_max  24.0

<font size = "4">

**Q5** Calculate race duration

<font size = "3">

- Read in the file "results_cleaned.csv" from the `quiz_data` folder, saving it as a DataFrame.

- The "milliseconds" column shows the race duration for each result measured in milliseconds. Create a new column called "race_duration_minutes" where we convert the race duration to minutes by dividing each millisecond value by 60,000 (which equals $6 \times 10^4$). Equivalently, you can multiply each millisecond value by $6 \times 10^{-4}$

- Group the data by **both** "raceId" and "constructorId" and calculate the average race duration in minutes for each group.

- Sort the data in descending order and then extract the raceId/constructorId pairs with the 5 slowest average times.

In [383]:
# your code here
df_cleaned = pd.read_csv("quiz_data/results_cleaned.csv")
df_cleaned["race_duration_minutes"] = df_cleaned["milliseconds"]/60000
df_cleaned.groupby(["raceId","constructorId"]).agg(
    race_minute_mean = ('race_duration_minutes', 'mean')
).sort_values(by = "race_minute_mean", ascending = False)


df_cleaned

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,laps,time,milliseconds,fastestLap,rank,fastestLapTime,fastestLapSpeed,statusId,race_duration_minutes
0,1,18,1,1,22,1,1,1,1,10.0,58,1:34:50.616,5690616.0,39,2,1:27.452,218.300,1,94.843600
1,2,18,2,2,3,5,2,2,2,8.0,58,+5.478,5696094.0,41,3,1:27.739,217.586,1,94.934900
2,3,18,3,3,7,7,3,3,3,6.0,58,+8.163,5698779.0,41,5,1:28.090,216.719,1,94.979650
3,4,18,4,4,5,11,4,4,4,5.0,58,+17.181,5707797.0,58,7,1:28.603,215.464,1,95.129950
4,5,18,5,1,23,3,5,5,5,4.0,58,+18.014,5708630.0,43,1,1:27.418,218.385,1,95.143833
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25655,25661,1086,825,210,20,13,16,16,16,0.0,69,\N,NaN,37,15,1:23.511,188.856,11,NaN
25656,25662,1086,848,3,23,17,17,17,17,0.0,69,\N,NaN,43,12,1:23.047,189.911,11,NaN
25657,25663,1086,849,3,6,19,18,18,18,0.0,69,\N,NaN,60,8,1:22.478,191.221,11,NaN
25658,25664,1086,852,213,22,16,19,19,19,0.0,68,\N,NaN,58,16,1:23.538,188.795,12,NaN
25659,25665,1086,822,51,77,8,20,20,20,0.0,65,\N,NaN,60,19,1:24.002,187.752,131,NaN

<font size = "4">

**Q6** Aggregate custom statistic

<font size = "3">

- Continue to use the DataFrame corresponding to the data in "results_cleaned.csv".

- When a driver finishes 1st, 2nd, or 3rd it is known as a "podium finish". Write a function that takes in a Pandas Series and returns the number of entries $\leq 3$.

- Group by "driverId" and then aggregate the following statistics: the average of the "points" column, and the number of podium finishes in the "positionOrder" column - use your custom function for this second statistic.

- Merge the aggregated data back into the original DataFrame.

In [ ]:
# your code here
def num_of_entries(rank):
    n = rank
    if n == "1":
        return n
    if n == "2":
        return n
    if n == "3":
        return n

df_cleaned["rank"].apply(num_of_entries).count()

np.int64(1068)

In [ ]:
df_cleaned.groupby(by = "driverId").agg(
    points_mean = ('points','mean'),
    count_positionOrder = ('positionOrder', 'count')
)

AttributeError: 'str' object has no attribute 'apply'

In [432]:
df_cleaned[["rank","positionOrder","driverId"]]

      rank  positionOrder  driverId
0        2              1         1
1        3              2         2
2        5              3         3
3        7              4         4
4        1              5         5
...    ...            ...       ...
25655   15             16       825
25656   12             17       848
25657    8             18       849
25658   16             19       852
25659   19             20       822

[25660 rows x 3 columns]

In [ ]:
count = 0